apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: default
  source:
    repoURL: https://github.com/jarededwards/kubefirst-local
    path: registry/crossplane/gcp/components/external-dns # todo probably remove /crossplane/ from here
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
