apiVersion: iam.gcp.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: external-dns
spec:
  forProvider:
    displayName: "external-dns-sa"
    description: "a service account for external dns to manage dns records"
  deletionPolicy: Delete
  providerConfigRef:
    name: default