---
apiVersion: compute.gcp.crossplane.io/v1beta1
kind: Network
metadata:
  name: kubefirst
spec:
  forProvider:
    autoCreateSubnetworks: true
    routingConfig:
      routingMode: REGIONAL
  providerConfigRef:
    name: default
# ---
# apiVersion: compute.gcp.upbound.io/v1beta1
# kind: Network
# metadata:
#   annotations:
#     upjet.upbound.io/timeout: "4800"
#     # meta.upbound.io/example-id: compute/v1beta1/network
#   labels:
#     name: kubefirst-network
#   name: kubefirst-network
# spec:
#   forProvider:
#     autoCreateSubnetworks: false
#     routingConfig:
#       routingMode: REGIONAL
#   providerConfigRef:
#     name: default