apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gcp-system
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  source:
    repoURL: https://github.com/jarededwards/kubefirst-local
    path: components/gcp-crossplane/gcp-system
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: upbound-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
