apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccount
metadata:
  annotations:
    meta.upbound.io/example-id: cloudplatform/v1beta1/serviceaccount
  labels:
    testing.upbound.io/example-name: example_service_account
  name: external-dns
spec:
  forProvider:
    displayName: external-dns
    description: service account for external dns to manage dns records 
  providerConfigRef:
    name: gcp-provider
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: cloudplatform/v1beta1/serviceaccountiammember
  labels:
    testing.upbound.io/example-name: service-account-iam-member
  name: external-dns-iam-member
spec:
  forProvider:
    member: serviceAccount:kubefirst-cli.svc.id.goog[external-dns/external-dns]
    role: "roles/iam.workloadIdentityUser"
    serviceAccountIdRef:
      name: external-dns
  providerConfigRef:
    name: gcp-provider
---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: cloudplatform/v1beta1/serviceaccountiammember
  labels:
    testing.upbound.io/example-name: service-account-iam-member
  name: external-dns-iam-member
spec:
  forProvider:
    member: serviceAccount:kubefirst-cli.svc.id.goog[external-dns/external-dns]
    role: "roles/owner"
    serviceAccountIdRef:
      name: external-dns
  providerConfigRef:
    name: gcp-provider


#! the below was working in the old provider
# apiVersion: iam.gcp.crossplane.io/v1alpha1
# kind: ServiceAccount
# metadata:
#   name: external-dns
#   annotations:
#     argocd.argoproj.io/sync-wave: "10"
# spec:
#   forProvider:
#     displayName: "external-dns"
#     description: "a service account for external dns to manage dns records"
#   deletionPolicy: Delete
#   providerConfigRef:
#     name: default
# ---
# apiVersion: iam.gcp.crossplane.io/v1alpha1
# kind: ServiceAccountPolicy
# metadata:
#   name: external-dns-policy
#   annotations:
#     argocd.argoproj.io/sync-wave: "10"
# spec:
#   forProvider:
#     serviceAccountRef:
#       name: external-dns
#     policy:
#       bindings:
#         # Ref: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
#         - role: roles/iam.workloadIdentityUser
#           members:
#             - serviceAccount:kubefirst-cli.svc.id.goog[external-dns/external-dns]
#         - role: roles/owner
#           members:
#             - serviceAccount:kubefirst-cli.svc.id.goog[external-dns/external-dns]
#         # - role: roles/dns.changes.create 
#         #   members:
#         #     - serviceAccount:kubefirst-cli.svc.id.goog[external-dns/external-dns]
#         # - role: roles/dns.resourceRecordSets.create
#         #   members:
#         #     - serviceAccount:kubefirst-cli.svc.id.goog[external-dns/external-dns]
#   providerConfigRef:
#     name: default