apiVersion: v1
data:
  project: ZGVmYXVsdA==
  type: Z2l0
  url: B64_ENCODED_GITHUB_OWNER_OR_ORGANIZATION==
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: kubefirst-repo
  namespace: argocd
type: Opaque
