apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: nebulous-oss
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: provider-gcp-creds
      key: creds
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: gcp-config
spec:
  podSecurityContext:
    fsGroup: 2000
  args:
  - '--debug'