apiVersion: kms.aws.crossplane.io/v1alpha1
kind: Key
metadata:
  name: vault-key
spec:
  providerConfigRef:
    name: default
  forProvider:
    keySpec: SYMMETRIC_DEFAULT
    keyUsage: ENCRYPT_DECRYPT
    policy: |-
      {
        "Version": "2012-10-17",
        "Id": "kms-key-policy",
        "Statement": [
          {
            "Sid": "Enable IAM User Permissions",
            "Effect": "Allow",
            "Principal": {
              "AWS": "arn:aws:iam::126827061464:root"
            },
            "Action": "kms:*",
            "Resource": "*"
          },
          {
            "Sid": "Allow access for Key Administrators",
            "Effect": "Allow",
            "Principal": {
              "AWS": [
                "arn:aws:iam::126827061464:root"
              ]
            },
            "Action": [
              "kms:Create*",
              "kms:Describe*",
              "kms:Enable*",
              "kms:List*",
              "kms:Put*",
              "kms:Update*",
              "kms:Revoke*",
              "kms:Disable*",
              "kms:Get*",
              "kms:Delete*",
              "kms:TagResource",
              "kms:UntagResource",
              "kms:ScheduleKeyDeletion",
              "kms:CancelKeyDeletion"
            ],
            "Resource": "*"
          },
          {
            "Sid": "Allow use of the key",
            "Effect": "Allow",
            "Principal": {
              "AWS": [
                "arn:aws:iam::126827061464:root"
              ]
            },
            "Action": [
              "kms:Encrypt",
              "kms:Decrypt",
              "kms:ReEncrypt*",
              "kms:GenerateDataKey*",
              "kms:DescribeKey"
            ],
            "Resource": "*"
          },
          {
            "Sid": "Allow attachment of persistent resources",
            "Effect": "Allow",
            "Principal": {
              "AWS": [
                "arn:aws:iam::126827061464:root"
              ]
            },
            "Action": [
              "kms:CreateGrant",
              "kms:ListGrants",
              "kms:RevokeGrant"
            ],
            "Resource": "*",
            "Condition": {
              "Bool": {
                "kms:GrantIsForAWSResource": "true"
              }
            }
          }
        ]
      }
    region: us-east-1
    tags:
    - tagKey: kubefast-vault-kms
      tagValue: v1
    - tagKey: cluster-name
      tagValue: kubefast
---
apiVersion: kms.aws.crossplane.io/v1alpha1
kind: Alias
metadata:
  name: vault-kubefast
spec:
  forProvider:
    region: us-east-1
    targetKeyIdRef:
      name: vault-key
  providerConfigRef:
    name: default