apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: amazon-eks-worker-node-policy-kubefast
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    roleNameRef:
      name: eks-worker-nodes-role-kubefast
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: amazon-ec2-container-registry-readonly-kubefast
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
    roleNameRef:
      name: eks-worker-nodes-role-kubefast
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: RolePolicyAttachment
metadata:
  name: amazon-eks-cni-policy-kubefast
spec:
  forProvider:
    policyArn: arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    roleNameRef:
      name: eks-worker-nodes-role-kubefast
  providerConfigRef:
    name: default
---
apiVersion: iam.aws.crossplane.io/v1beta1
kind: Role
metadata:
  name: eks-worker-nodes-role-kubefast
spec:
  forProvider:
    assumeRolePolicyDocument: |
      {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Effect": "Allow",
                "Principal": {
                    "Service": [
                        "ec2.amazonaws.com"
                    ]
                },
                "Action": [
                    "sts:AssumeRole"
                ]
            }
        ]
      }
    tags:
      - key: k2
        value: v2
      - key: crossplane-kind	#* note: proactively added this tag due to argocd showing a diff
        value: role.iam.aws.crossplane.io
      - key: crossplane-name	#* note: proactively added this tag due to argocd showing a diff
        value: eks-worker-nodes-role-kubefast
      - key: crossplane-providerconfig	#* note: proactively added this tag due to argocd showing a diff
        value: default
  providerConfigRef:
    name: default