apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: kubefast-public-subnet-1
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1a
    cidrBlock: 10.0.4.0/24
    vpcIdRef:
      name: kubefast-vpc
    mapPublicIPOnLaunch: true
    tags:
      - key: Name
        value: kubefirst-vpc-public-us-east-1a
      - key: crossplane-kind	
        value: vpc.ec2.aws.crossplane.io	
      - key: crossplane-name	
        value: kubefast-public-subnet-1
      - key: crossplane-providerconfig	
        value: default
      - key: ClusterName
        value: kubefast
      - key: ProvisionedBy
        value: kubefirst
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: kubefast-public-subnet-2
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1b
    cidrBlock: 10.0.5.0/24
    vpcIdRef:
      name: kubefast-vpc
    mapPublicIPOnLaunch: true
    tags:
      - key: Name
        value: kubefirst-vpc-public-us-east-1b
      - key: crossplane-kind	
        value: vpc.ec2.aws.crossplane.io	
      - key: crossplane-name	
        value: kubefast-public-subnet-2
      - key: crossplane-providerconfig	
        value: default
      - key: ClusterName
        value: kubefast
      - key: ProvisionedBy
        value: kubefirst
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: kubefast-public-subnet-3
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1c
    cidrBlock: 10.0.6.0/24
    vpcIdRef:
      name: kubefast-vpc
    mapPublicIPOnLaunch: true
    tags:
      - key: Name
        value: kubefirst-vpc-public-us-east-1c
      - key: crossplane-kind	
        value: vpc.ec2.aws.crossplane.io	
      - key: crossplane-name	
        value: kubefast-public-subnet-3
      - key: crossplane-providerconfig	
        value: default
      - key: ClusterName
        value: kubefast
      - key: ProvisionedBy
        value: kubefirst
  providerConfigRef:
    name: default