apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: kubefast-private-subnet-1
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1a
    cidrBlock: 10.0.1.0/24
    vpcIdRef:
      name: kubefast-vpc
    mapPublicIPOnLaunch: true # todo remove this line in private subnets
    tags:
      - key: ClusterName
        value: kubefast
      - key: Name
        value: kubefirst-vpc-private-us-east-1a
      - key: ProvisionedBy
        value: kubefirst
      - key: crossplane-kind
        value: subnet.ec2.aws.crossplane.io
      - key: crossplane-name
        value: kubefast-private-subnet-1
      - key: crossplane-providerconfig
        value: default
      - key: kubernetes.io/role/elb
        value: 1
      - key: kubernetes.io/cluster/kubefast
        value: shared
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: kubefast-private-subnet-2
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1b
    cidrBlock: 10.0.2.0/24
    vpcIdRef:
      name: kubefast-vpc
    mapPublicIPOnLaunch: true # todo remove this line in private subnets
    tags:
      - key: ClusterName
        value: kubefast
      - key: Name
        value: kubefirst-vpc-private-us-east-1b
      - key: ProvisionedBy
        value: kubefirst
      - key: crossplane-kind
        value: subnet.ec2.aws.crossplane.io
      - key: crossplane-name
        value: kubefast-private-subnet-2
      - key: crossplane-providerconfig
        value: default
      - key: kubernetes.io/role/elb
        value: 1
      - key: kubernetes.io/cluster/kubefast
        value: shared
  providerConfigRef:
    name: default
---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: Subnet
metadata:
  name: kubefast-private-subnet-3
spec:
  forProvider:
    region: us-east-1
    availabilityZone: us-east-1c
    cidrBlock: 10.0.3.0/24
    vpcIdRef:
      name: kubefast-vpc
    mapPublicIPOnLaunch: true # todo remove this line in private subnets
    tags:
      - key: ClusterName
        value: kubefast
      - key: Name
        value: kubefirst-vpc-private-us-east-1c
      - key: ProvisionedBy
        value: kubefirst
      - key: crossplane-kind
        value: subnet.ec2.aws.crossplane.io
      - key: crossplane-name
        value: kubefast-private-subnet-3
      - key: crossplane-providerconfig
        value: default
      - key: kubernetes.io/role/elb
        value: 1
      - key: kubernetes.io/cluster/kubefast
        value: shared
  providerConfigRef:
    name: default