apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: kubefast-vpc
spec:
  forProvider:
    region: us-east-1
    cidrBlock: 10.0.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
    instanceTenancy: default
    tags:
      - key: ClusterName
        value: kubefast
      - key: Name
        value: kubefast-vpc
      - key: ProvisionedBy
        value: kubefirst
      - key: crossplane-kind	
        value: vpc.ec2.aws.crossplane.io	
      - key: crossplane-name	
        value: kubefast-vpc	
      - key: crossplane-providerconfig	
        value: default
  providerConfigRef:
    name: default