apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gcp-cloud
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/jarededwards/kubefirst-local
    path: registry/crossplane/gcp/components/cloud
    targetRevision: localhost-experience
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true