# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: providerconfig-gcp-components
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "20"
# spec:
#   project: default
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: argocd
#   source:
#     repoURL: https://github.com/jarededwards/kubefirst-local
#     path: registry/crossplane/gcp/components/providerconfig
#     targetRevision: localhost-experience
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true