# ---
# # GCP Admin service account secret - used by GCP ProviderConfig
# apiVersion: v1
# kind: Secret
# metadata:
#   namespace: crossplane-system
#   name: provider-gcp
# type: Opaque
# data:
#   credentials.json: <REPLACEME>
---
# GCP ProviderConfig with service account secret reference
apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: nebulous-oss
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: provider-gcp
      key: credentials.json