apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    upjet.upbound.io/timeout: "4800"
    # meta.upbound.io/example-id: compute/v1beta1/network
  labels:
    my-label: kubefirst
  name: kubefirst
spec:
  forProvider:
    autoCreateSubnetworks: false
    routingMode: REGIONAL
  providerConfigRef:
    name: kubefirst-cli-provider