apiVersion: v1
kind: Secret
metadata:
  name: jet-aws-creds
  namespace: crossplane-system
type: Opaque
data:
  credentials: <REPLACEME> #! do not change the <REPLACEME> token.
---
apiVersion: aws.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default # todo i.e. atlantis power?
spec:
  credentials:
    source: Secret
    secretRef:
      name: jet-aws-creds
      namespace: crossplane-system
      key: credentials