apiVersion: ecr.aws.crossplane.io/v1beta1
kind: Repository
metadata:
  name: xp-test-repo
  labels:
    region: us-east-1
spec:
  forProvider:
    region: us-east-1
    imageScanningConfiguration:
      scanOnPush: true
    imageTagMutability: IMMUTABLE
  providerConfigRef:
    name: default