apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: provider-aws-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/jarededwards/kubefirst-local
    path: registry/crossplane/aws/components/provider
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true