apiVersion: v1
data:
  password: B64_ENCODED_GITHUB_ACCESS_TOKEN== 
  url: B64_ENCODED_GITHUB_OWNER_OR_ORGANIZATION== # github.com/jarededwards
  username: a3ViZWZpcnN0LWxvY2Fs # kubefirst-local
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repo-creds
  name: kubefirst-local-creds
  namespace: argocd
type: Opaque
---
apiVersion: v1
data:
  project: ZGVmYXVsdA== # default
  type: Z2l0 # git
  url: B64_ENCODED_GITHUB_OWNER_OR_ORGANIZATION== # github.com/jarededwards
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: kubefirst-repo
  namespace: argocd
type: Opaque
