apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: external-dns
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 6.5.4
    helm:
      releaseName: external-dns
      values: |
        initContainers:
          - image:  gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
            name: workload-identity-initcontainer
            command:
            - '/bin/bash'
            - '-c'
            - |
              curl -sS -H 'Metadata-Flavor: Google' 'http://169.254.169.254/computeMetadata/v1/instance/service-accounts/default/token' --retry 30 --retry-connrefused --retry-max-time 60 --connect-timeout 3 --fail --retry-all-errors > /dev/null && exit 0 || echo 'Retry limit exceeded. Failed to wait for metadata server to be available. Check if the gke-metadata-server Pod in the kube-system namespace is healthy.' >&2; exit 1
        serviceAccount:
          create: true
          annotations:
            iam.gke.io/gcp-service-account: external-dns@kubefirst-cli.iam.gserviceaccount.com
        domainFilters:
          - kubefirst.dev
        provider: google
        google: 
          project: kubefirst-cli
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
