---
apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: kubefast
  labels:
    cluster: "kubefast"
    managed-by: "crossplane"
spec:
  deletionPolicy: Orphan
  forProvider:
    region: us-east-1
    roleArnRef:
      name: eks-role
    resourcesVpcConfig:
      endpointPrivateAccess: true
      endpointPublicAccess: true
      subnetIdRefs:
        - name: kubefast-public-subnet-1 # todo private
        - name: kubefast-public-subnet-2 # todo private
        - name: kubefast-public-subnet-3 # todo private
      securityGroupIdRefs:
        - name: kubefast-eks-sg
    version: "1.22"
  writeConnectionSecretToRef:
    name: cluster-conn
    namespace: crossplane-system
  providerConfigRef:
    name: default