apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: kubefast-workers
  labels:
    cluster: "kubefast"
spec:
  deletionPolicy: Delete # Orphan
  forProvider:
    region: us-east-1
    clusterNameRef:
      name: kubefast
    subnetRefs:
      - name: kubefast-public-subnet-1 # todo private
      - name: kubefast-public-subnet-2 # todo private
      - name: kubefast-public-subnet-3 # todo private
    nodeRoleRef:
      name: eks-worker-nodes-role-kubefast
    scalingConfig:
      desiredSize: 2
      maxSize: 2
      minSize: 2 
  providerConfigRef:
    name: default