apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: kubefast-workers-3
  labels:
    cluster: "kubefast"
spec:
  deletionPolicy: Delete # Orphan
  forProvider:
    region: us-east-1
    clusterNameRef:
      name: kubefast-xp
    subnetRefs:
      - name: kubefast-public-subnet-1 # todo private
      - name: kubefast-public-subnet-2 # todo private
      - name: kubefast-public-subnet-3 # todo private
    nodeRoleRef:
      name: eks-worker-nodes-role-kubefast
    scalingConfig:
      desiredSize: 2
      maxSize: 2
      minSize: 2 
  providerConfigRef:
    name: default    
---
apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: kubefast-workers-4
  labels:
    cluster: "kubefast"
spec:
  deletionPolicy: Delete # Orphan
  forProvider:
    region: us-east-1
    clusterNameRef:
      name: kubefast-xp
    subnetRefs:
      - name: kubefast-public-subnet-1 # todo private
      - name: kubefast-public-subnet-2 # todo private
      - name: kubefast-public-subnet-3 # todo private
    nodeRoleRef:
      name: eks-worker-nodes-role-kubefast
    scalingConfig:
      desiredSize: 2
      maxSize: 2
      minSize: 2 
    tags:
      - key: Name
        value: kubefast-workers-4
      - key: ProvisionedBy
        value: kubefirst
      - key: crossplane-kind
        value: eks.aws.crossplane.io
      - key: crossplane-name
        value: kubefast-workers-4
      - key: crossplane-providerconfig
        value: default
      - key: kubernetes.io/cluster/kubefast
        value: owned
  providerConfigRef:
    name: default    