apiVersion: eks.aws.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: kubefirst-workers
  labels:
    cluster: "kubefirst"
spec:
  forProvider:
    region: us-east-1
    clusterNameRef:
      name: kubefirst
    subnetRefs:
      - name: kubefirst-public-subnet-1 # todo private
      - name: kubefirst-public-subnet-2 # todo private
      - name: kubefirst-public-subnet-3 # todo private
    nodeRoleRef:
      name: eks-worker-nodes-role-kubefast-kubefast
    scalingConfig:
      desiredSize: 2
      maxSize: 2
      minSize: 2 
  providerConfigRef:
    name: default