apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-issuers-components
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "110"
spec:
  project: default
  source:
    repoURL: https://github.com/jarededwards/kubefirst-local
    path: registry/gke-apps/cert-issuers # todo how to architect our yaml
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-issuers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
