apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jet-aws
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/jarededwards/kubefirst-local
    path: registry/crossplane/jet-aws
    targetRevision: localhost-experience
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true