apiVersion: ecr.aws.jet.crossplane.io/v1alpha2
kind: Repository
metadata:
  name: xp-coming-for-you-dan
spec:
  forProvider:
    region: us-east-1
    imageScanningConfiguration:
      - scanOnPush: true
    imageTagMutability: "IMMUTABLE"
    tags:
      key1: thisrules